version: "3.8"
services:
  mymongodb:
    image: "mongo:5.0"
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    depends_on:
      - mymongodb
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  data: