version: "3.8"
services:
  mymongodb:
    image: "mongo:5.0"
    ports:
      - "27017:27017"
    volumes:
      - mongodata-prod:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "4000:4000"
    depends_on:
      - mymongodb
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongodata-prod: