- hosts: ec2_master
  gather_facts: no
  tasks:
    - name: Running K8s Master Role
      include_role:
        name: k8s_master

- hosts: ec2_slave
  gather_facts: no
  tasks:
    - name: Running K8s Slave Role
      include_role:
        name: k8s_slave